def get_scpoli_defaults():
    return {
        "dataset_id": "pbmc-immune",
        "model_name_version": 5.0,
        "num_prototypes": 8,
        "hidden_dim": 64,
        "latent_dims": 8,
        "batch_size_version": 2,
        "batch_size": 512,
        "fine_tuning_epochs": 0,
        "custom_cross_val": False,
        "description": "",
        "experiment_name": "scpoli",
        "condition_key": "study",
        "cell_type_key": "cell_type",
        # "epochs": 300,
        "linear_eval": False,
        "only_eval": False,
        "use_early_stopping": False,
        "debug": False,
        "pretraining_epochs": 300,
        "training_type": 'pretrain'
    }


def get_swav_defaults():
    scpoli_defaults = get_scpoli_defaults()
    swav_specific_defaults = {
        "experiment_name": "",
        "dump_name_version": 4,
        "nmb_crops": [8],
        "augmentation_type": "knn",
        "size_crops": [224],
        "min_scale_crops": [0.14],
        "max_scale_crops": [1],
        "crops_for_assign": [0, 1],
        "temperature": 0.1,
        "epsilon": 0.05,
        "sinkhorn_iterations": 3,
        "latent_dims": 8,
        "feat_dim": 8,
        "num_prototypes": 128,
        "queue_length": 0,
        "epoch_queue_starts": 15,
        "batch_size": 512,
        "base_lr": 4.8,
        "final_lr": 0,
        "freeze_prototypes_niters": 313,
        "wd": 1e-6,
        "warmup_epochs": 10,
        "start_warmup": 0,
        "cvae_reg": 0,
        "dist_url": "env://",
        "world_size": -1,
        "rank": 0,
        "local_rank": 0,
        "workers": 10,
        "checkpoint_freq": 25,
        "use_fp16": False,
        "sync_bn": "pytorch",
        "syncbn_process_group_size": 8,
        "seed": 31,
        "model": "",
        "optimizer": "",
        "lr_schedule": "",
        "queue": None,
        "train_loader": "",
        "training_stats": "",
        "condition_key": "study",
        "cell_type_key": "cell_type",
        "device": "cuda",
        "freezable_prototypes": False,  # should be true
        "cvae_loss_scaler": 0.0001,
        "prot_decoding_loss_scaler": 5,
        # 64
        "hidden_mlp": 1024,
        # 16
        "swav_dim": 64,
        "use_projector": False,
        "model_version": 2,
        "train_decoder": False,
        "longest_path": 3,
        "dimensionality_reduction": None, 
        'k_neighbors': 10
    }
    scpoli_defaults.update(swav_specific_defaults)
    return scpoli_defaults


def get_merged_defaults():
    return {
        "dataset_id": "pbmc-immune",
        "model_name_version": 4.0,
        "num_prototypes": 128,  # from swav
        "hidden_dim": 64,
        "latent_dims": 8,  # from swav
        "batch_size_version": 2,
        "batch_size": 512,  # from swav
        "fine_tuning_epochs": 100,
        "custom_cross_val": False,
        "description": "",
        "experiment_name": "",  # from swav
        "condition_key": "study",
        "cell_type_key": "cell_type",
        "epochs": 300,
        "linear_eval": False,
        "only_eval": False,
        "use_early_stopping": False,
        "debug": False,
        "dump_name_version": 4,
        "nmb_crops": [8],
        "augmentation_type": "knn",
        "size_crops": [224],
        "min_scale_crops": [0.14],
        "max_scale_crops": [1],
        "crops_for_assign": [0, 1],
        "temperature": 0.1,
        "epsilon": 0.05,
        "sinkhorn_iterations": 3,
        "feat_dim": 8,
        "queue_length": 0,
        "epoch_queue_starts": 15,
        "base_lr": 4.8,
        "final_lr": 0,
        "freeze_prototypes_niters": 313,
        "wd": 1e-6,
        "warmup_epochs": 10,
        "start_warmup": 0,
        "cvae_reg": 0,
        "dist_url": "env://",
        "world_size": -1,
        "rank": 0,
        "local_rank": 0,
        "workers": 10,
        "checkpoint_freq": 25,
        "use_fp16": False,
        "sync_bn": "pytorch",
        "syncbn_process_group_size": 8,
        "seed": 31,
        "model": "",
        "optimizer": "",
        "lr_schedule": "",
        "queue": None,
        "train_loader": "",
        "training_stats": "",
        "device": "cuda",
        "freezable_prototypes": False,
        "cvae_loss_scaler": 0.0001,
        "prot_decoding_loss_scaler": 5,
        "hidden_mlp": 1024,
        "swav_dim": 64,
        "use_projector": False,
        "model_version": 2,
    }
